### ISSUE TITLE
Link on active node

### ISSUE THREAD

**Issue by collinss99** [RonnyWeiss/Apex-Fancy-Tree-Select#1]
Hi Ronny

We've been using your fancy tree plugin since upgrading to APEX 20. It's amazing and has helped us our enormously.  We have noticed one thing (unless we've configured it wrong). Once an active node is selected the link from that active node does not fire. Just thought you might like to know

Thanks

Simo

**Comment by RonnyWeiss** [comment]
Hello

Thank you for your ticket. I know this problem and will try to solve it in next version. It's default handling of fancy treee but maybe I can workaround this

Kind regards

Ronny

**Comment by collinss99** [comment]
That’s great. Thank you

Simon

**Comment by RonnyWeiss** [comment]
Should be fixed in Version 2.1.4.2

**Comment by collinss99** [comment]
Hi Ronny

Sorry to be a pain but was excited to here about the update with the fix for active node. However, we've installed the new version and the problem remains. Is there anything that we might have missed like a new config setting?

Thanks

Simon

**Comment by RonnyWeiss** [comment]
Sorry I mean Version 2.1.4.3
